version: '3.3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: spark
      MYSQL_PASSWORD: tmvkzm
      MYSQL_ROOT_PASSWORD: tmvkzm
    ports:
      - '3306:3306'
    volumes:
      - "./mysql_data:/var/lib/mysql"
